apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniogitops
spec:
  project: default
  source:
    repoURL: https://github.com/ngdangkietswe/swe-infrastructure.git
    targetRevision: HEAD
    path: ./k8s/minio
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
    namespace: swe-prod
  sources: [ ]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true